### ISSUE TITLE
Calculate balances

### ISSUE THREAD

**Issue by mdragaschnig** [graphsense/graphsense-ethereum-transformation#2]
Based on 
https://medium.com/google-cloud/how-to-query-balances-for-all-ethereum-addresses-in-bigquery-fb594e4034a7

and including genesis transfers from 
https://github.com/openethereum/openethereum/blob/main/crates/ethcore/res/chainspec/foundation.json

**Comment by mdragaschnig** [comment]
Has been overhauled in https://github.com/graphsense/graphsense-ethereum-transformation/commit/789fec3d28feb29f20e82eed0ea81d6a85f95bbd

which influences https://github.com/graphsense/graphsense-ethereum-etl/issues/1

**Comment by defconst** [comment]
Implemented in 169d65a2ebfb5bcb61e34a61031591eb129f6a57
