### ISSUE TITLE
Add fields for number of code transactions/relations

### ISSUE THREAD

**Issue by myrho** [graphsense/graphsense-ethereum-transformation#9]
Since code transactions (tx value = 0) are different from value transactions, add distinct calculated fields for the number of code transactions, resp. code relations. Suggestions for field names:

address:
* `in_degree_code`
* `out_degree_code`
* `no_incoming_txs_code`
* `no_outgoing_txs_code`

relations:
* `no_transactions_code`

**Comment by soad003** [comment]
@myrho added the fields to the address table in the tron branch. Will be available for eth aswell as soon as we merge. Regarding the relations I don't think we need that there. Either all txs are code txs or none on a relation. Note: the fields count relations and txs to smart contracts (not zero-value). I can add fields for zero value txs as well if needed
